select * from customer limit 10;

-- Q1: What is the total revenue generated by male vs. female customers?
select gender , sum(purchase_amount) as revenue from customer group by gender;

-- Q2: Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3: Which are the top 5 products with the highest average review rating?
select item_purchased , round(avg(review_rating):: numeric,2) as "Average Product Rating" from customer group by item_purchased  order by avg(review_rating) desc limit 5;

-- Q4: Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, round(avg(purchase_amount)::numeric, 2) from customer where shipping_type IN ('Express', 'Standard') group by shipping_type ;

-- Q5: Do subscribed customers spend more? (Comparison of average spend and total revenue between subscribers and non-subscribers).
select case when subscription_status = 'Yes' then 'Subscribers' else 'Non-subscribers' end as subscription_staus, count(customer_id) as total_customers, round(avg(purchase_amount)::numeric, 2) as avg_spend , sum(purchase_amount) as revenue from customer group by subscription_status order by revenue, avg_spend desc;

-- Q6: Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased , ROUND(
          100 * sum(CASE WHEN discount_applied = 'Yes' THEN 1 else 0 END) 
           / COUNT(*), 
           2
       ) AS discount_rate from customer  group by item_purchased order by discount_rate desc limit 5;

-- Q7: Segment customers into "New," "Returning," and "Loyal" based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id , previous_purchases, 
case 
	when previous_purchases = 1 then 'New' 
	when previous_purchases between 2 and 10 then 'Returning'  
	else 'Loyal' 
end as customer_segment from customer)
select customer_segment, count(*) as no_of_customers from customer_type group by customer_segment;

-- Q8: What are the top 3 most purchased products within each category?
with item_counts as(
select category , item_purchased, count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as items_rank
from customer group by category, item_purchased
) 
select items_rank,category,item_purchased, total_orders
from item_counts where items_rank <= 3 order by items_rank;

-- Q9: Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select  case when subscription_status = 'Yes' then 'Subscribers' else 'Non-subscribers' end as subscription_staus , count(customer_id) as repeat_buyers from customer where previous_purchases > 5 group by subscription_status;

-- Q10: What is the revenue contribution of each age group?
select age_group , sum(purchase_amount) as revenue from customer group by age_group order by revenue desc;
